### ISSUE TITLE
Supporting armv8 and the Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by ghost** [ReturnInfinity/BareMetal#24]
I'm wondering at what point is the armv8 architecture going to be supported, as I just found out that the Raspberry Pi 3 Model B uses this architecture. It would be interesting to have BareMetal run on a Pi.

I could start working on this, if you want. I've wanted to purchase a Pi for a while now, and I'm betting there's emulators for armv8 too that I could use to get it started.

**Comment by IanSeyler** [comment]
Absolutely! This is a valid target as I did not want to deal with 32-bit hardware.

The big question is how is the wired network device connected internally? I thought it was via USB for previous models.

**Comment by IanSeyler** [comment]
Based on this [block diagram](https://www.element14.com/community/servlet/JiveServlet/downloadImage/38-24733-365232/1259-900/pi3-block-diagram-rev4.png) it looks like USB would be needed.

**Comment by tay10r** [comment]
Okay. I think implementing the Ethernet transmit and receive functions should still be doable.

**Comment by tay10r** [comment]
Have you heard of (Keys[https://github.com/keystone-engine/keystone]

**Comment by tay10r** [comment]
I published a Debian package for binutils-aarch64-elf, which is usable for the kernel development. I'll add a corresponding gcc-aarch64-elf when it comes time to start compiling BMFS and Alloy.

The Debian package for bmfs-aarch64-elf is available via:

```
sudo add-apt-repository ppa:taylorcholberton/binutils-aarch64-elf
sudo apt update
sudo apt install binutils-aarch64-elf
```
It's currently available for Ubuntu:

 - 17.10 (Artful)
 - 17.04 (Zesty)
 - 16.10 (Yakkety)

**Comment by tay10r** [comment]
I think the memory allocation should be written in C. It's going to work exactly the same as the x86_64 architecture, and writing it in C will make it easily unit tested, able to be shared among all supported architectures and easier to maintain. Although this would make the kernel a mixture of C and assembly and not pure assembly, it would have very little or no performance cost. It may even increase performance of the GCC optimizations are good enough. What do you think?

**Comment by IanSeyler** [comment]
This would be the board to target initially: https://www.pine64.org/?page_id=1459

**Comment by tay10r** [comment]
I have that board. Haven't got around to testing it yet.

**Comment by TanishShinde** [comment]
Well Pine64 is great but if to go for Raspberry Pi 3, it would be great, please join this slack channel I created and we should have a team meeting tommorow

**Comment by TanishShinde** [comment]
we could have it at 7:30 PM My Time, 2:30 PM at Ian's Time and 2:30 PM at Taylor's Time

**Comment by TanishShinde** [comment]
Slack Channel Url https://www.baremetalos.slack.com

**Comment by TanishShinde** [comment]
I Will Send Invites To Everybody Through Skype If It Works For You All

**Comment by IanSeyler** [comment]
Closing this for now. Can re-open a new issue when a use case comes along.
