### ISSUE TITLE
Write flag for ahci

### ISSUE THREAD

**Issue by lupo1977** [ReturnInfinity/BareMetal#63]
it seems in the code of ahci.asm

```
	mov eax, 0x00010005		; 1 PRDTL Entry, Command FIS Length = 20 bytes
	cmp ebx, 0x35			; Was a write requested?
	jne ahci_io_skip_writebit	; If not, skip setting the write flag
	bts ebx, 6			; Set the write flag (bit 6)
ahci_io_skip_writebit:
	stosd				; DW 0 - Description Information

```

There is a bug, the write flag bit 6 should be set for eax?

**Comment by IanSeyler** [comment]
@lupo1977 You are correct. The write flag (bit 6) needs to be set for `DW 0`
The correct code is `bts eax, 6` and I will make that change.

**Comment by maalos** [comment]
> The correct code is bts eax, 6 and I will make that change.
proceeds to use an imaginary register `abx` instead of `eax`

**Comment by IanSeyler** [comment]
Haha. Oops. I should probably use the registers that the CPU is aware of.
